name: Deploy Docker to Aliyun

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # 可选：手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: ${{ secrets.ALIYUN_PORT }}
          script: |
            # 1. 进入项目目录（假设项目已克隆到服务器）
            cd  ~/wrokkspace/notes-app-server

            # 2. 拉取最新代码（需配置Git凭据或SSH Key）
            git pull origin master
            
            echo 'clientId=${{ secrets.CLIENT_ID }}' >  ~/wrokkspace/notes-app-server/.env &&
            echo 'clientSecret=${{ secrets.CLIENT_SECRET }}' >>  ~/wrokkspace/notes-app-server/.env

            # 3. 构建Docker镜像（基于新代码）
            docker build -t notes .

            # 4. 重启容器
            docker stop notes-app || true
            docker rm notes-app || true
            docker run -d --name notes-app -p 3000:3000 notes

            # 可选：清理旧镜像
            docker system prune -f