name: Deploy Docker to Aliyun

on:
  push:
    branches: ['master']
  workflow_dispatch: # 可选：手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: ${{ secrets.ALIYUN_PORT }}
          script: |
            mkdir -p ~/workspace

            # 如果目录不存在就 clone，一次性操作
            if [ ! -d ~/workspace/notes-app-server ]; then
                cd ~/workspace
                git clone https://github.com/你的仓库路径.git notes-app-server
            fi

            cd ~/workspace/notes-app-server

            git pull origin master

            cat <<EOF > .env
            clientId=${{ secrets.CLIENT_ID }}
            clientSecret=${{ secrets.CLIENT_SECRET }}
            EOF

            docker build -t notes .
            docker stop notes-app || true
            docker rm notes-app || true
            docker run -d --name notes-app -p 3000:3000 notes
            docker system prune -f
